name: Codacy Security Scan Utils

on:
  pull_request:

jobs:
  codacy-security-scan-coverage-reporter:
    uses: dymexjs/reusable_workflows/.github/workflows/codacy-analysis.yml@main
    secrets:
      codacy-api-token: ${{ secrets.CODACY_API_TOKEN }}
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
