name: "Update version and publish"

on:
  release:
    types: [released]

jobs:
  update_version:
    name: Update Version
    uses: dymexjs/reusable_workflows/.github/workflows/update-packagejson-version.yml@main
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # updated CHANGELOG back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write

  update_changelog:
    name: Update Changelog
    needs: [update_version]
    uses: dymexjs/reusable_workflows/.github/workflows/update-changelog.yml@main
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # updated CHANGELOG back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write

  publish:
    name: Npm Publish
    needs: [update_changelog]
    uses: dymexjs/reusable_workflows/.github/workflows/publish-npm.yml@main
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    permissions:
      id-token: write
